<?xml version="1.0" encoding="utf-8"?>
<report>
	<activity
		result="Failed"
		duration="0ms"
		durationms="0"
		type="root"
		rid="4cbfbc533b16871"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		user="pandey"
		host="FLR1622"
		rxversion="5.4.6.0"
		osversion="Windows 7 Service Pack 1 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		language="en-US"
		screenresolution="3200x1080"
		timestamp="6/28/2016 3:32:03 PM"
		timestampiso="2016-06-28T13:32:03"
		timeoutfactor="1"
		module="SelectSourceAndTargetUserCode">
		<detail>
			SelectSourceAndTargetUserCode
		</detail>
		<varbindings/>
		<item
			timeRelativeToTestSuiteStartTime="00:29.799"
			timeRelativeToTestModuleStartTime="00:29.799"
			timeWallClock="15:32:32"
			time="00:29.799"
			level="Error"
			category="User"
			errimg=".\SelectSourceAndTargetUserCode.cs_20160628_153200_aab053a8_trace.jpg"
			errthumb=".\SelectSourceAndTargetUserCode.cs_20160628_153200_aab053a8_trace_thumb.jpg">
			<message>
				The test run has been aborted by the user.
			</message>
			<metainfo
				loglvl="Error"/>
		</item>
	</activity>
</report>
