<?xml version="1.0" encoding="utf-8"?>
<report>
	<activity
		result="Failed"
		duration="0ms"
		durationms="0"
		type="root"
		rid="d33c3a07d5b0c4"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		user="pandey"
		host="FLR1622"
		rxversion="5.4.5.19886"
		osversion="Windows 7 Service Pack 1 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		language="en-US"
		screenresolution="3200x1080"
		timestamp="4/15/2016 9:35:36 AM"
		timestampiso="2016-04-15T07:35:36"
		timeoutfactor="1"
		module="ClickOnPackage">
		<detail>
			ClickOnPackage
		</detail>
		<varbindings/>
		<item
			timeRelativeToTestSuiteStartTime="00:15.445"
			timeRelativeToTestModuleStartTime="00:15.445"
			timeWallClock="09:35:52"
			time="00:15.445"
			level="Error"
			category="User"
			errimg=".\ClickOnPackage.cs_20160415_093533_79feeaa5_trace.jpg"
			errthumb=".\ClickOnPackage.cs_20160415_093533_79feeaa5_trace_thumb.jpg">
			<message>
				The test run has been aborted by the user.
			</message>
			<metainfo
				loglvl="Error"/>
		</item>
	</activity>
</report>
